export 'listar_alumnos.dart' show listarAlumnos;
export 'eliminar_alumnos.dart' show eliminarAlumnos;
export 'agregar_alumno.dart' show agregarAlumno;
export 'actualizar_alumno.dart' show actualizarAlumno;
export 'listar_asignaturas.dart' show listarAsignaturas;
export 'eliminar_asignatura.dart' show eliminarAsignatura;
export 'agregar_asignatura.dart' show agregarAsignatura;
export 'actualizar_asignatura.dart' show actualizarAsignatura;
export 'agregar_asignatura_alumno.dart' show agregarAsignaturaAlumno;
